### ISSUE TITLE
Column segmentsCabinCode

### ISSUE THREAD

**Issue by gilberto-009199** [dilwong/FlightPrices#3]
Can you explain to me what coach, premium coach, first, business is?

We have the following configuration:
coach||coach	
coach	
coach||coach||coach
coach||coach||coach||coach
premium coach
first||coach
premium coach||coach
coach||premium coach
first||first
coach||first
first
premium coach||premium coach
business
premium coach||coach||coach
first||first||first
coach||coach||premium coach
business||business
business||coach
first||coach||coach
coach||coach||first
coach||premium coach||coach
first||first||coach
coach||first||first
coach||first||coach
business||coach||coach
coach||business
premium coach||premium coach||coach
coach||premium coach||premium coach
first||coach||first
coach||business||coach
coach||coach||coach||premium coach
business||business||coach
coach||coach||coach||first
coach||coach||business
coach||business||business
coach||coach||first||first

**Comment by gilberto-009199** [comment]
I appreciate any help

**Comment by gilberto-009199** [comment]
@dilwong  or @MatheusBorgesFaria  , thanks

**Comment by MatheusBorgesFaria** [comment]
Hey Gil.

Maybe this version of the repository is more up-to-date than the one at https://github.com/MatheusBorgesFaria/FlightPrices.

My undergraduate thesis was based on this repository,

https://docs.google.com/document/d/1gFv3zBasBL1ji1jpFuucGUw7uibV2aQq4Sp67pi8Iu4/edit?usp=sharing maybe it will help you with something. This document is in Portuguese, but I imagine that Google Translate would solve this.

I collected and structured in Postgres more than 210 million lines of flight prices, if you want I can send you the data.

I don't know how to answer your question because the last time I touched this was a long time ago. If I can help with anything else, I'm available.

Cheers, @gilberto-009199 

I would like to take this opportunity to thank you for starting the repository, @dilwong ! It helped me graduate.

**Comment by MatheusBorgesFaria** [comment]
https://www.linkedin.com/in/matheus-borges-faria-2a71811bb/ contacting me would be easier through linkedin

**Comment by gilberto-009199** [comment]
Thank you very much, I was trying to do a regression
![image](https://github.com/user-attachments/assets/41805dac-4046-448d-881d-42a4ed9a10e0)
But there is still a lot of refinement to be done and perhaps there are not enough columns/features
I will look at your work,
Cheers to you @MatheusBorgesFaria

**Comment by gilberto-009199** [comment]
Vou fechar a issue em breve!!

**Comment by gilberto-009199** [comment]
I'm going to make a small contribution.
I made a jupiter notebook, which can be found at:
https://gist.github.com/gilberto-009199/fbccf055d4d6b24792b8045efe1b7e3b
Based on a subset of:
https://github.com/dilwong/FlightPrices
In this notebook I create 3 machine learning models, which are:
+ Simple linear regression
+ Decision tree
+ Random forest
+ Gradient descent (Ridge, Lasso and Elastic Net)

**Comment by gilberto-009199** [comment]
Obrigado, a vcs!!! @MatheusBorgesFaria  e @dilwong

**Comment by dilwong** [comment]
@MatheusBorgesFaria Glad you found this repo a helpful starting place! 😄

**Comment by dilwong** [comment]
@gilberto-009199 I'm not sure I understand your original question.  Coach, premium coach, first, and business are different cabin classes on an airplane.  You can pay extra money for a more comfortable experience on an airplane (i.e. first class is more luxurious than coach, which is the same as economy).

**Comment by gilberto-009199** [comment]
thanks @dilwong
